export default {
    SIGN_UP_ACTION: "SIGN_UP_ACTION",
    AUTH_ACTION: "AUTH_ACTION",
    USER_DATA_RESPONSE: "USER_DATA_RESPONSE",
    USER_DATA_REQUEST: "USER_DATA_REQUEST",
    USER_DATA_ERROR: "USER_DATA_ERROR",

    CREATE_BOT_ACTION: "CREATE_BOT_ACTION",
    GET_ALL_BOTS_ACTION: "GET_ALL_BOTS_ACTION",
    BOTS_DATA_RESPONSE: "BOTS_DATA_RESPONSE",
    BOTS_DATA_REQUEST: "BOTS_DATA_REQUEST",
    BOTS_DATA_ERROR: "BOTS_DATA_ERROR",

    GET_ALL_SCENARIES: "GET_ALL_SCENARIES",
    ADD_NEW_SCENARIO: "ADD_NEW_SCENARIO",
    ADD_NEW_TRIGGER: "ADD_NEW_TRIGGER",
    SINGLE_BOT_DATA_RESPONSE: "SINGLE_BOT_DATA_RESPONSE",
    SINGLE_BOT_DATA_REQUEST: "SINGLE_BOT_DATA_REQUEST",
    SINGLE_BOT_DATA_ERROR: "SINGLE_BOT_DATA_ERROR"
}